---
- name: update web 1 server
  hosts: web1
  become: yes
  become_method: sudo
  tasks:
  - name: apache is installed and latest version
    yum:
      name: httpd
      state: latest
  - name: write index.html file
    shell: echo "Hello from server web1 !" >> /var/www/html/index.html
  - name: chmod file to be readable by httpd process
    file:
      path: /var/www/html/index.html
      mode: 644
  - name: Make sure httpd service is running and reloaded at startup
    ansible.builtin.systemd:
      state: started
      name: httpd
      enabled: yes
- name: update web 2 server
  hosts: web2 
  become: yes
  become_method: sudo
  tasks:
  - name: apache is installed and latest version
    yum:
      name: httpd
      state: latest
  - name: write index.html file
    shell: echo "Hello from server web2 !" >> /var/www/html/index.html
  - name: chmod file to be readable by httpd process
    file:
      path: /var/www/html/index.html
      mode: 644
  - name: Make sure httpd service is running and reloaded at startup
    ansible.builtin.systemd:
      state: started
      name: httpd
      enabled: yes